export const ERROR_CODES = {
  // Generic
  INTERNAL_ERROR: "INTERNAL_ERROR",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RATE_LIMITED: "RATE_LIMITED",
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",

  // Auth
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",

  // Pets
  PET_NOT_FOUND: "PET_NOT_FOUND",
  PET_ALREADY_ARCHIVED: "PET_ALREADY_ARCHIVED",

  // Reminders
  REMINDER_NOT_FOUND: "REMINDER_NOT_FOUND",
  REMINDER_ALREADY_COMPLETED: "REMINDER_ALREADY_COMPLETED",

  // Devices
  DEVICE_TOKEN_NOT_FOUND: "DEVICE_TOKEN_NOT_FOUND",
  INVALID_PUSH_TOKEN: "INVALID_PUSH_TOKEN",

  // Vaccinations
  VACCINATION_NOT_FOUND: "VACCINATION_NOT_FOUND",

  // Medications
  MEDICATION_NOT_FOUND: "MEDICATION_NOT_FOUND",

  // Vet visits
  VET_VISIT_NOT_FOUND: "VET_VISIT_NOT_FOUND",

  // Expenses
  EXPENSE_NOT_FOUND: "EXPENSE_NOT_FOUND",
  EXPENSE_SOURCE_LOCKED: "EXPENSE_SOURCE_LOCKED",

  // Weights
  WEIGHT_RECORD_NOT_FOUND: "WEIGHT_RECORD_NOT_FOUND",

  // Travel
  TRAVEL_PLAN_NOT_FOUND: "TRAVEL_PLAN_NOT_FOUND",
  CHECKLIST_ITEM_NOT_FOUND: "CHECKLIST_ITEM_NOT_FOUND",
  TEMPLATE_NOT_FOUND: "TEMPLATE_NOT_FOUND",

  // Lost pets
  LOST_REPORT_NOT_FOUND: "LOST_REPORT_NOT_FOUND",
  LOST_REPORT_ALREADY_ACTIVE: "LOST_REPORT_ALREADY_ACTIVE",
  LOST_REPORT_NOT_ACTIVE: "LOST_REPORT_NOT_ACTIVE",
  PUBLIC_REPORT_NOT_FOUND: "PUBLIC_REPORT_NOT_FOUND",

  // Places
  PLACE_NOT_FOUND: "PLACE_NOT_FOUND",
  REVIEW_NOT_FOUND: "REVIEW_NOT_FOUND",
  MISSING_LOCATION: "MISSING_LOCATION",

  // Family sharing
  PET_ACCESS_DENIED: "PET_ACCESS_DENIED",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  CANNOT_REMOVE_OWNER: "CANNOT_REMOVE_OWNER",
  CANNOT_CHANGE_OWNER_ROLE: "CANNOT_CHANGE_OWNER_ROLE",
  INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
  INVITATION_EXPIRED: "INVITATION_EXPIRED",
  INVITATION_ALREADY_USED: "INVITATION_ALREADY_USED",
  ALREADY_A_MEMBER: "ALREADY_A_MEMBER",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
