export const ERROR_CODES = {
  // Generic
  INTERNAL_ERROR: "INTERNAL_ERROR",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RATE_LIMITED: "RATE_LIMITED",
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",

  // Auth
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",

  // Pets
  PET_NOT_FOUND: "PET_NOT_FOUND",
  PET_ALREADY_ARCHIVED: "PET_ALREADY_ARCHIVED",

  // Reminders
  REMINDER_NOT_FOUND: "REMINDER_NOT_FOUND",
  REMINDER_ALREADY_COMPLETED: "REMINDER_ALREADY_COMPLETED",

  // Devices
  DEVICE_TOKEN_NOT_FOUND: "DEVICE_TOKEN_NOT_FOUND",
  INVALID_PUSH_TOKEN: "INVALID_PUSH_TOKEN",

  // Vaccinations
  VACCINATION_NOT_FOUND: "VACCINATION_NOT_FOUND",

  // Medications
  MEDICATION_NOT_FOUND: "MEDICATION_NOT_FOUND",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
